spring.application.name=aws-cigarette-smokers-problem
server.port=8081

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

grpc.server.port=9091
grpc.server.reflection-service-enabled=true

aws.region=eu-central-1
aws.dynamodb.table-name=Games

logging.level.org.springframework.data.repository.config.RepositoryConfigurationDelegate=WARN
