spring.application.name=cigarette-smokers-problem-client
server.port=8080
# application-dev.properties
grpc.client.game-server.address=static://18.158.182.62:9091
grpc.client.game-server.negotiationType=plaintext
