syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.umutavci.grpc";
option java_outer_classname = "GameProto";

service GameService {
  rpc JoinGame (JoinRequest) returns (JoinResponse);
  rpc JoinSpecificTable (JoinSpecificRequest) returns (JoinResponse);
  rpc LeaveTable (LeaveRequest) returns (LeaveResponse);
  rpc GetTableStatus (TableRequest) returns (TableResponse);
  rpc AllTables (Empty) returns (AllTablesResponse);
  rpc getAllUsersOnTable (TableRequest) returns (UsersOnTableResponse);
  rpc StreamGameEvents (GameEventRequest) returns (stream GameEventResponse);

}

message JoinRequest {
  string username = 1;
}

message JoinSpecificRequest {
  string username = 1;
  string tableId = 2;
}

message JoinResponse {
  string message = 1;
  string tableId = 2;
}

message LeaveRequest {
  string username = 1;
  string tableId = 2;
}

message LeaveResponse {
  string message = 1;
}

message TableRequest {
  string tableId = 1;
}

message TableResponse {
  string tableId = 1;
  bool started = 2;
  bool booked = 3;
  int32 playerCount = 4;
  repeated string smokers = 5;
}

message AllTablesResponse {
  repeated TableResponse tables = 1;
}

message UsersOnTableResponse {
  repeated JoinRequest users = 1;
}

message GameEventRequest {
  string tableId = 1;
}

message GameEventResponse {
  string message = 1;
  string tableId = 2;
}

message Empty {}

